export default {
    name: "page",
    title: "Page",
    type: "document",
    groups: [
        { name: "content", title: "Main Content", default: true },
        { name: "hero", title: "Hero Section" },
        { name: "seo", title: "SEO & Social" },
        { name: "pageinfo", title: "Page Info" },
    ],
    fields: [
        {
            name: "title",
            title: "Title",
            type: "string",
            group: "pageinfo",
            validation: (r: any) => r.required(),
        },
        {
            name: "slug",
            title: "Slug",
            type: "slug",
            group: "pageinfo",
            options: { source: "title" },
            validation: (r: any) => r.required(),
        },
        {
            name: "seo",
            title: "SEO",
            type: "seo",
            group: "seo",
            initialValue: { _type: "seo" },
        },

        // Optional: allow a page-level hero, then sections
        {
            name: "hero",
            title: "Hero",
            type: "section.heroSplitCta",
            group: "hero",
        },
        {
            name: "sections",
            title: "Sections",
            type: "array",
            group: "content",
            of: [
                { type: "section.heroSplitCta" },
                { type: "section.simpleText" },
                { type: "section.attackChainDiagram" },
                { type: "section.benefitCards" },
                { type: "section.signalGroups" },
                { type: "section.globalCoverage" },
                { type: "section.jsonExample" },
                { type: "section.primaryUseCase" },
                { type: "section.secondaryUseCases" },
                { type: "section.productSplit" },
                { type: "section.privacyCompliance" },
                { type: "section.finalCta" },
                { type: "section.faqList" },
                { type: "section.statsGrid" },
                { type: "section.featureList" },
                { type: "section.integrationMethods" },
                { type: "section.featureHighlight" },
                { type: "section.domainLookup" },
                { type: "section.pricingOverview" },
                { type: "section.ctaBanner" },
                { type: "section.dataSources" },
                { type: "section.useCaseGrid" },
                { type: "section.falsePositiveReduction" },
                { type: "section.dataDictionary" },
                { type: "section.documentList" },
                { type: "section.featureGrid" },
                { type: "section.anchorLinks" },
                { type: "section.mediaFeature" },
                { type: "section.pillarRouter" },
                { type: "section.trustEvidence" },
                { type: "section.iconList" },
                { type: "section.twoColumnFeature" },
                { type: "section.threeColumnDetailed" },
                { type: "section.contact" },
                { type: "section.centeredImage" },
                { type: "section.pricingTable" },
                { type: "section.circularFeatures" },
                { type: "section.whoShouldApply" },
                { type: "section.detectionGrid" },
                { type: "section.comparisonTable" },
                { type: "section.comparisonGrid" },
            ],
        },
    ],
    preview: {
        select: { title: "title", slug: "slug.current" },
        prepare({ title, slug }: any) {
            return { title, subtitle: slug ? `/${slug}` : "" };
        },
    },
};

