export default {
    name: "pricingPage",
    title: "Pricing Page",
    type: "document",
    initialValue: {
        slug: { current: "pricing" },
        sections: [
            {
                _type: "section.anchorLinks",
                title: "Jump to Pricing",
                behavior: "switch",
                selectedAnchors: [
                    { anchor: "pricing-phishing-alerts", label: "Phishing Alerts" },
                    { anchor: "pricing-api", label: "API" },
                    { anchor: "pricing-cloud-shares", label: "Cloud Shares" },
                ],
            },
            {
                _type: "section.pricingOverview",
                title: "Phishing Alerts",
                anchor: "pricing-phishing-alerts",
            },
            {
                _type: "section.pricingOverview",
                title: "API",
                anchor: "pricing-api",
            },
            {
                _type: "section.pricingOverview",
                title: "Cloud Shares",
                anchor: "pricing-cloud-shares",
            },
        ],
    },
    fields: [
        { name: "title", title: "Title", type: "string", validation: (r: any) => r.required() },
        {
            name: "slug",
            title: "Slug",
            type: "slug",
            options: { source: "title" },
            initialValue: { current: "pricing" },
            validation: (r: any) => r.required(),
        },
        { name: "seo", title: "SEO", type: "seo" },
        {
            name: "hero",
            title: "Hero",
            type: "section.heroSplitCta",
        },
        {
            name: "sections",
            title: "Sections",
            type: "array",
            of: [
                { type: "section.heroSplitCta" },
                { type: "section.simpleText" },
                { type: "section.attackChainDiagram" },
                { type: "section.benefitCards" },
                { type: "section.signalGroups" },
                { type: "section.globalCoverage" },
                { type: "section.jsonExample" },
                { type: "section.primaryUseCase" },
                { type: "section.secondaryUseCases" },
                { type: "section.productSplit" },
                { type: "section.privacyCompliance" },
                { type: "section.finalCta" },
                { type: "section.faqList" },
                { type: "section.statsGrid" },
                { type: "section.featureList" },
                { type: "section.integrationMethods" },
                { type: "section.featureHighlight" },
                { type: "section.domainLookup" },
                { type: "section.pricingOverview" },
                { type: "section.ctaBanner" },
                { type: "section.dataSources" },
                { type: "section.useCaseGrid" },
                { type: "section.falsePositiveReduction" },
                { type: "section.documentList" },
                { type: "section.featureGrid" },
                { type: "section.anchorLinks" },
                { type: "section.mediaFeature" },
                { type: "section.pillarRouter" },
            ],
        },
        { name: "headline", title: "Headline (Legacy)", type: "string" },
        { name: "subheadline", title: "Subheadline (Legacy)", type: "text", rows: 3 },
    ],
    preview: { prepare: () => ({ title: "Pricing Page" }) },
};
