export default {
    name: "pricingPage",
    title: "Pricing Page",
    type: "document",
    fields: [
        { name: "title", title: "Title", type: "string", validation: (r: any) => r.required() },
        {
            name: "slug",
            title: "Slug",
            type: "slug",
            options: { source: "title" },
            initialValue: { current: "pricing" },
            validation: (r: any) => r.required(),
        },
        { name: "seo", title: "SEO", type: "seo" },
        {
            name: "hero",
            title: "Hero",
            type: "section.heroSplitCta",
        },
        {
            name: "sections",
            title: "Sections",
            type: "array",
            of: [
                { type: "section.heroSplitCta" },
                { type: "section.simpleText" },
                { type: "section.attackChainDiagram" },
                { type: "section.benefitCards" },
                { type: "section.signalGroups" },
                { type: "section.globalCoverage" },
                { type: "section.jsonExample" },
                { type: "section.primaryUseCase" },
                { type: "section.secondaryUseCases" },
                { type: "section.productSplit" },
                { type: "section.privacyCompliance" },
                { type: "section.finalCta" },
                { type: "section.faqList" },
                { type: "section.statsGrid" },
                { type: "section.featureList" },
                { type: "section.integrationMethods" },
                { type: "section.featureHighlight" },
                { type: "section.domainLookup" },
                { type: "section.pricingOverview" },
                { type: "section.ctaBanner" },
                { type: "section.dataSources" },
                { type: "section.useCaseGrid" },
                { type: "section.falsePositiveReduction" },
                { type: "section.documentList" },
                { type: "section.featureGrid" },
            ],
        },
        { name: "headline", title: "Headline (Legacy)", type: "string" },
        { name: "subheadline", title: "Subheadline (Legacy)", type: "text", rows: 3 },
    ],
    preview: { prepare: () => ({ title: "Pricing Page" }) },
};
