export default {
    name: "useCase",
    title: "Use Case",
    type: "document",
    fields: [
        { name: "title", title: "Title", type: "string", validation: (r: any) => r.required() },
        {
            name: "slug",
            title: "Slug",
            type: "slug",
            options: { source: "title" },
            validation: (r: any) => r.required(),
        },
        {
            name: "audience",
            title: "Audience",
            type: "string",
            options: { list: ["MSSPs / MDR", "Banks & Fintech (B2B2C)", "Platforms & SaaS", "Data & Analytics"] },
            validation: (r: any) => r.required(),
        },
        { name: "summary", title: "Summary", type: "text", rows: 3 },
        {
            name: "hero",
            title: "Hero",
            type: "section.heroSplitCta",
        },
        {
            name: "sections",
            title: "Sections",
            type: "array",
            of: [
                { type: "section.heroSplitCta" },
                { type: "section.simpleText" },
                { type: "section.attackChainDiagram" },
                { type: "section.benefitCards" },
                { type: "section.signalGroups" },
                { type: "section.globalCoverage" },
                { type: "section.jsonExample" },
                { type: "section.primaryUseCase" },
                { type: "section.secondaryUseCases" },
                { type: "section.productSplit" },
                { type: "section.privacyCompliance" },
                { type: "section.finalCta" },
                { type: "section.faqList" },
                { type: "section.statsGrid" },
                { type: "section.featureList" },
                { type: "section.integrationMethods" },
                { type: "section.featureHighlight" },
                { type: "section.domainLookup" },
                { type: "section.pricingOverview" },
                { type: "section.ctaBanner" },
                { type: "section.dataSources" },
                { type: "section.useCaseGrid" },
                { type: "section.falsePositiveReduction" },
                { type: "section.documentList" },
                { type: "section.featureGrid" },
            ],
        },
        { name: "problem", title: "Problem", type: "text", rows: 5 },
        { name: "solution", title: "Solution", type: "text", rows: 5 },
        { name: "outcomes", title: "Outcomes", type: "array", of: [{ type: "string" }] },
        { name: "recommendedIntegrations", title: "Recommended integrations", type: "array", of: [{ type: "string" }] },
        { name: "primaryCta", title: "Primary CTA", type: "cta" },
        { name: "seo", title: "SEO", type: "seo" },
    ],
    preview: {
        select: { title: "title", audience: "audience" },
        prepare({ title, audience }: any) {
            return { title, subtitle: audience };
        },
    },
};
