#!/usr/bin/env node
/**
 * WU26 — pull canonical site stats from the CertaLake coverage feed.
 *
 * Fetches coverage.json from the public CertaLake stats bucket and writes the
 * raw values to lib/site-stats.generated.ts. Wired as `prebuild`, so every
 * deploy pulls fresh figures; the daily cron (/api/cron/refresh-stats →
 * deploy hook) makes the pull happen at least once a day.
 *
 * FAIL-SOFT: on any fetch/validation failure this script warns and exits 0,
 * leaving the last-known-good generated file in place — a feed hiccup must
 * never break the build or put a broken number on the site (the
 * certificate-counter lesson). Validation, flooring and display formatting
 * live in lib/site-stats.ts, NOT here — this script records the feed
 * honestly and only refuses values that are not positive finite numbers.
 *
 * Run manually: npm run stats:refresh
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const FEED_BASE =
  process.env.CERTALAKE_STATS_URL ||
  process.env.NEXT_PUBLIC_WEBSITE_STATS_URL ||
  "https://pub-f2251a15327b429780b7ee354ff19e1b.r2.dev";

// Keep in sync with COMMITTED.domainsMonitored in lib/site-stats.ts — used
// only for the loud warning below; the module enforces the actual floor.
const COMMITTED_DOMAINS_FLOOR = 368_000_000;

const OUT_PATH = join(dirname(fileURLToPath(import.meta.url)), "..", "lib", "site-stats.generated.ts");

function metric(value) {
  return typeof value === "number" && Number.isFinite(value) && value > 0 ? value : null;
}

function render(stats) {
  const field = (v) => (v === null ? "null as number | null" : `${v} as number | null`);
  const strField = (v) => (v === null ? "null as string | null" : `${JSON.stringify(v)} as string | null`);
  return `/**
 * AUTO-GENERATED by scripts/refreshSiteStats.mjs — do not hand-edit.
 * Raw values as last fetched from the CertaLake coverage feed. Validation,
 * flooring and display formatting happen in lib/site-stats.ts, never here.
 * A null means the feed did not provide that field.
 */
export const feedStats = {
  domainsMonitored: ${field(stats.domainsMonitored)},
  ipsHostingDomains: ${field(stats.ipsHostingDomains)},
  ipv4Indexed: ${field(stats.ipv4Indexed)},
  networksProfiled: ${field(stats.networksProfiled)},
  /** \`updated\` timestamp reported by the feed itself. */
  feedUpdated: ${strField(stats.feedUpdated)},
  /** When the refresh script last wrote this file. */
  fetchedAt: ${strField(stats.fetchedAt)},
  source: ${strField(stats.source)},
};
`;
}

async function main() {
  const url = `${FEED_BASE.replace(/\/$/, "")}/coverage.json`;
  let coverage;
  try {
    const res = await fetch(url, { signal: AbortSignal.timeout(15_000) });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    coverage = await res.json();
  } catch (err) {
    console.warn(`⚠ site-stats refresh skipped — could not fetch ${url} (${err?.message ?? err}). Keeping last-known-good lib/site-stats.generated.ts.`);
    return;
  }

  const stats = {
    domainsMonitored: metric(coverage.domains),
    // The feed's threat_ips is a different measure — only infrastructure_ips
    // maps to "IPs hosting domains". Absent → null → committed value is used.
    ipsHostingDomains: metric(coverage.infrastructure_ips),
    ipv4Indexed: metric(coverage.ips),
    networksProfiled: metric(coverage.asns),
    feedUpdated: typeof coverage.updated === "string" ? coverage.updated : null,
    fetchedAt: new Date().toISOString(),
    source: url,
  };

  if (stats.domainsMonitored === null && stats.ipv4Indexed === null && stats.networksProfiled === null) {
    console.warn(`⚠ site-stats refresh skipped — ${url} returned no usable metrics. Keeping last-known-good lib/site-stats.generated.ts.`);
    return;
  }

  writeFileSync(OUT_PATH, render(stats));
  console.log(`✓ site-stats refreshed from ${url} (feed updated ${stats.feedUpdated ?? "unknown"}).`);

  if (stats.domainsMonitored !== null && stats.domainsMonitored < COMMITTED_DOMAINS_FLOOR) {
    console.warn(
      `\n⚠ CertaLake feed reports ${stats.domainsMonitored.toLocaleString()} domains — BELOW the committed DuckLake floor of ${COMMITTED_DOMAINS_FLOOR.toLocaleString()}.\n` +
        `  The site keeps displaying the committed floor (see FLOOR RULE in lib/site-stats.ts).\n` +
        `  Upstream fix needed: the coverage.json generator should calculate the domain count from DuckLake gold (~368M), not its current source.\n`,
    );
  }
}

main();
