#!/usr/bin/env node
/**
 * WU26 — pull canonical site stats from the CertaLake coverage feed.
 *
 * Fetches coverage.json from the public CertaLake stats bucket and writes the
 * raw values to lib/site-stats.generated.ts. Wired as `prebuild`, so every
 * deploy pulls fresh figures; the daily cron (/api/cron/refresh-stats →
 * deploy hook) makes the pull happen at least once a day.
 *
 * FAIL-SOFT: on any fetch/validation failure this script warns and exits 0,
 * leaving the last-known-good generated file in place — a feed hiccup must
 * never break the build or put a broken number on the site (the
 * certificate-counter lesson). Validation, flooring and display formatting
 * live in lib/site-stats.ts, NOT here — this script records the feed
 * honestly and only refuses values that are not positive finite numbers.
 *
 * "ONLY REFUSES VALUES THAT ARE NOT POSITIVE FINITE NUMBERS" WAS THE HOLE.
 * 4,320,469,598 is a positive finite number and it is also more IPv4 addresses
 * than exist, so it passed this script, passed lib/site-stats.ts, and rendered
 * as "4.3B IPv4 addresses indexed" on the front page. Since 2026-08-22 this
 * script also rejects a value outside its BOUND — a bad producer must not be
 * recorded as last-known-good, because last-known-good is what the site falls
 * back to on the next fetch failure. An out-of-bound value is dropped to null
 * and the committed figure covers it.
 *
 * Per-figure as-of: coverage.json now carries an `as_of` map (each figure's own
 * timestamp) alongside `updated` (when the file was built). We record the
 * figures' as-of, not the build time — a daily total rendered beside an hourly
 * counter must show when the TOTAL was measured, not when the file was written.
 *
 * Run manually: npm run stats:refresh
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const FEED_BASE =
  process.env.CERTALAKE_STATS_URL ||
  process.env.NEXT_PUBLIC_WEBSITE_STATS_URL ||
  "https://pub-f2251a15327b429780b7ee354ff19e1b.r2.dev";

// Keep in sync with COMMITTED.domainsMonitored in lib/site-stats.ts — used
// only for the loud warning below; the module enforces the actual floor.
//
// ⚠️ THIS CONSTANT HAS NOW GONE STALE TWICE, and both times it produced a
// CONFIDENT WRONG INSTRUCTION rather than silence. It sat at 368_000_000 while
// the real floor moved, then at 395_865_413 after the corpus was refiltered to
// exclude ~40M dead names — and on that run it told the reader the feed was
// "BELOW the committed floor" and that an upstream fix was needed, when the
// feed had just become MORE honest and the upstream fix was the thing that had
// happened. A stale duplicate of a number is worse than no check at all: it
// speaks with the authority of a guard while pointing the wrong way.
// If you change COMMITTED.domainsMonitored, change this in the same commit.
const COMMITTED_DOMAINS_FLOOR = 362_714_858;

const IPV4_ADDRESS_SPACE = 2 ** 32; // 4,294,967,296

// Keep in sync with BOUNDS in lib/site-stats.ts and COVERAGE_BOUNDS in
// riskscore/orchestration/website_stats.py. Three gates, same limits: the
// producer, the pull, and the render. The impossible figure crossed all three
// when none of them existed.
const BOUNDS = {
  domainsMonitored: [100_000_000, 2_000_000_000],
  ipsHostingDomains: [100_000, IPV4_ADDRESS_SPACE],
  ipv4Indexed: [1_000_000_000, IPV4_ADDRESS_SPACE],
  networksProfiled: [10_000, 120_000],
};

const OUT_PATH = join(dirname(fileURLToPath(import.meta.url)), "..", "lib", "site-stats.generated.ts");

function metric(key, value) {
  if (typeof value !== "number" || !Number.isFinite(value) || value <= 0) return null;
  const bound = BOUNDS[key];
  if (bound && (value < bound[0] || value > bound[1])) {
    console.error(
      `✗ feed ${key} = ${value.toLocaleString()} is outside its bound ` +
        `[${bound[0].toLocaleString()}, ${bound[1].toLocaleString()}] — REJECTED, not recorded.\n` +
        `  The producer (riskscore/orchestration/website_stats.py) is publishing a figure it ` +
        `should have refused. Fix it there; do not widen the bound here.`,
    );
    return null;
  }
  return value;
}

function render(stats) {
  const field = (v) => (v === null ? "null as number | null" : `${v} as number | null`);
  const strField = (v) => (v === null ? "null as string | null" : `${JSON.stringify(v)} as string | null`);
  return `/**
 * AUTO-GENERATED by scripts/refreshSiteStats.mjs — do not hand-edit.
 * Raw values as last fetched from the CertaLake coverage feed. Validation,
 * flooring and display formatting happen in lib/site-stats.ts, never here.
 * A null means the feed did not provide that field.
 */
export const feedStats = {
  domainsMonitored: ${field(stats.domainsMonitored)},
  ipsHostingDomains: ${field(stats.ipsHostingDomains)},
  ipv4Indexed: ${field(stats.ipv4Indexed)},
  networksProfiled: ${field(stats.networksProfiled)},
  /** Per-figure as-of from the feed's \`as_of\` block — when each figure was
   *  measured, NOT when the file was built. A figure with no as-of does not
   *  get to borrow another figure's freshness. */
  asOf: {
    domainsMonitored: ${strField(stats.asOf.domainsMonitored)},
    ipsHostingDomains: ${strField(stats.asOf.ipsHostingDomains)},
    ipv4Indexed: ${strField(stats.asOf.ipv4Indexed)},
    networksProfiled: ${strField(stats.asOf.networksProfiled)},
  },
  /** \`updated\` timestamp reported by the feed itself — the file's build time. */
  feedUpdated: ${strField(stats.feedUpdated)},
  /** When the refresh script last wrote this file. */
  fetchedAt: ${strField(stats.fetchedAt)},
  source: ${strField(stats.source)},
};
`;
}

async function main() {
  const url = `${FEED_BASE.replace(/\/$/, "")}/coverage.json`;
  let coverage;
  try {
    const res = await fetch(url, { signal: AbortSignal.timeout(15_000) });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    coverage = await res.json();
  } catch (err) {
    console.warn(`⚠ site-stats refresh skipped — could not fetch ${url} (${err?.message ?? err}). Keeping last-known-good lib/site-stats.generated.ts.`);
    return;
  }

  // Per-figure as-of, falling back to the file's build time only when the feed
  // predates the as_of block. `updated` is when the FILE was written; it is not
  // any figure's as-of, and treating it as one is how a 13-hour-old total came
  // to be rendered as though it were live.
  // A figure that is null has no as-of. Stamping one would say "measured just
  // now" about a number the feed never supplied.
  const asOf = (key, value) => {
    if (value === null) return null;
    const v = coverage?.as_of?.[key];
    return typeof v === "string" ? v : typeof coverage.updated === "string" ? coverage.updated : null;
  };

  const values = {
    domainsMonitored: metric("domainsMonitored", coverage.domains),
    // The feed's threat_ips is a different measure — only infrastructure_ips
    // maps to "IPs hosting domains". Absent → null → committed value is used.
    ipsHostingDomains: metric("ipsHostingDomains", coverage.infrastructure_ips),
    ipv4Indexed: metric("ipv4Indexed", coverage.ips),
    networksProfiled: metric("networksProfiled", coverage.asns),
  };

  const stats = {
    ...values,
    feedUpdated: typeof coverage.updated === "string" ? coverage.updated : null,
    asOf: {
      domainsMonitored: asOf("domains", values.domainsMonitored),
      ipsHostingDomains: asOf("infrastructure_ips", values.ipsHostingDomains),
      ipv4Indexed: asOf("ips", values.ipv4Indexed),
      networksProfiled: asOf("asns", values.networksProfiled),
    },
    fetchedAt: new Date().toISOString(),
    source: url,
  };

  // A figure the producer itself refused ships as null with the reason in
  // `warnings`. Surface it — a silent null becomes a silent fallback to the
  // committed value, which is exactly how a dead producer stays invisible.
  if (Array.isArray(coverage.warnings) && coverage.warnings.length) {
    console.error(`✗ the coverage producer reported ${coverage.warnings.length} bound violation(s):`);
    for (const w of coverage.warnings) console.error(`    ${w}`);
  }

  if (stats.domainsMonitored === null && stats.ipv4Indexed === null && stats.networksProfiled === null) {
    console.warn(`⚠ site-stats refresh skipped — ${url} returned no usable metrics. Keeping last-known-good lib/site-stats.generated.ts.`);
    return;
  }

  writeFileSync(OUT_PATH, render(stats));
  console.log(`✓ site-stats refreshed from ${url} (feed updated ${stats.feedUpdated ?? "unknown"}).`);

  if (stats.domainsMonitored !== null && stats.domainsMonitored < COMMITTED_DOMAINS_FLOOR) {
    console.warn(
      `\n⚠ Feed reports ${stats.domainsMonitored.toLocaleString()} domains — BELOW the committed floor of ${COMMITTED_DOMAINS_FLOOR.toLocaleString()}.\n` +
        `  The site keeps displaying the committed floor (see FLOOR RULE in lib/site-stats.ts).\n` +
        `  TWO CAUSES LOOK IDENTICAL HERE and they need opposite responses:\n` +
        `    - a LAGGING feed (producer stale/degraded)  -> flooring is correct, fix the producer;\n` +
        `    - a MORE HONEST feed (population corrected)  -> flooring is WRONG and is holding a\n` +
        `      stale higher number up. Lower COMMITTED.domainsMonitored to match, and this\n` +
        `      constant with it.\n` +
        `  Check which before acting: compare the feed's definitions.domains against what\n` +
        `  COMMITTED was measured over. The 2026-08-29 dead-name correction was the second kind.\n`,
    );
  }
}

main();
